# Generated by Django 4.1.7 on 2023-03-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_alter_orderdetail_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_status',
            field=models.CharField(choices=[('order place', 'order place'), ('packing', 'packing'), ('in transit', 'in transit'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], max_length=20),
        ),
    ]
