# Generated by Django 4.1.7 on 2023-03-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_alter_cartdetail_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='total_price',
            field=models.FloatField(blank=True),
        ),
    ]
